{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sha512/unspecified/sha512-unspecified.module",
    "group": "KHash",
    "module": "sha512",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "sha512.klib",
          "url": "sha512-tvossimulatorarm64-unspecified.klib",
          "size": 19607,
          "sha512": "3e608f572b8e36a87bd592986ffb68e2e75407709fc21bdad4324033c96d32567c94f0e85fcb27cbc7a83ecca0a0f421e221221fafbfa71702f356d830163943",
          "sha256": "9655620d4d9f6b5fedcbc47cefc90719e2d6b7d2892956570fc6f490025b8ca0",
          "sha1": "0ef7315f5632de8731617d4b1def75386c256d7c",
          "md5": "331b7fa8da0a1cbabc9d5cbd0f63e93f"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "sha512-tvossimulatorarm64-metadata.jar",
          "url": "sha512-tvossimulatorarm64-unspecified-metadata.jar",
          "size": 261,
          "sha512": "9bb70273146dc9c9cf088fcd7bce9677e66a4356b61381efcb3d9bef6b2818d509772060a3b3f69cf49dac68a801d086f953d50019f8e803d9b7a720a5d8bdc7",
          "sha256": "4023299732f29f75d61845166190fda276bdbbc38c985a693bba35d9888cddb7",
          "sha1": "9df58aa1d633f5dc078352a12920a3f07abf3468",
          "md5": "e2b0c7c49df16119f833b0982ed991fb"
        }
      ]
    }
  ]
}
