{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sha256/unspecified/sha256-unspecified.module",
    "group": "KHash",
    "module": "sha256",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "sha256.klib",
          "url": "sha256-iosx64-unspecified.klib",
          "size": 19364,
          "sha512": "0fd6a08d5ee3af32b39df74fddb2cbbc12320dec7ea827a84194f0e95ac22624641d5b8dc83fc8b4b4794f1a35d0f02c8d29953c274066b046b0b042f3375873",
          "sha256": "6c84d74014d7213c9b626c3565ac30f36206d84cb0c171ff7114f257743f9074",
          "sha1": "023be6f19b17faa5db61eb310ecf923e54d87fe5",
          "md5": "80569dc32dc7cb8f1fb27c82edb55136"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "sha256-iosx64-metadata.jar",
          "url": "sha256-iosx64-unspecified-metadata.jar",
          "size": 261,
          "sha512": "9bb70273146dc9c9cf088fcd7bce9677e66a4356b61381efcb3d9bef6b2818d509772060a3b3f69cf49dac68a801d086f953d50019f8e803d9b7a720a5d8bdc7",
          "sha256": "4023299732f29f75d61845166190fda276bdbbc38c985a693bba35d9888cddb7",
          "sha1": "9df58aa1d633f5dc078352a12920a3f07abf3468",
          "md5": "e2b0c7c49df16119f833b0982ed991fb"
        }
      ]
    }
  ]
}
