{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sha512/unspecified/sha512-unspecified.module",
    "group": "KHash",
    "module": "sha512",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "sha512.klib",
          "url": "sha512-iosx64-unspecified.klib",
          "size": 19496,
          "sha512": "448e673f7c67c2b1e0091d5924aef84f28985ca1c33330c831ed55bbce8642bb11180d8cf7a36abcb00a373b65c98afdaeb5f561bcf356178abd6782a78be9e1",
          "sha256": "1dc6b3930378a383054e5e27a35d455dac2c638c5369804788d231ef4f17352c",
          "sha1": "32e101224fecb7e8b0730df021bc23da2feee40b",
          "md5": "8d0b133621cd15fb3cecea4dcc477e39"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "sha512-iosx64-metadata.jar",
          "url": "sha512-iosx64-unspecified-metadata.jar",
          "size": 261,
          "sha512": "9bb70273146dc9c9cf088fcd7bce9677e66a4356b61381efcb3d9bef6b2818d509772060a3b3f69cf49dac68a801d086f953d50019f8e803d9b7a720a5d8bdc7",
          "sha256": "4023299732f29f75d61845166190fda276bdbbc38c985a693bba35d9888cddb7",
          "sha1": "9df58aa1d633f5dc078352a12920a3f07abf3468",
          "md5": "e2b0c7c49df16119f833b0982ed991fb"
        }
      ]
    }
  ]
}
