{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sha256/unspecified/sha256-unspecified.module",
    "group": "KHash",
    "module": "sha256",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "sha256.klib",
          "url": "sha256-iosarm32-unspecified.klib",
          "size": 19379,
          "sha512": "ad8a82862e9fd966ebfb63a9f7601666e4533d45eb43cd4dfc8dbcc726b6a79f831d59925aeee5d532855c61f66b7f5bc900a707440586b0426b8a9c82bab93c",
          "sha256": "98c3428fc00149a97eff0b86fedf740a6809e9b69ab6affd5a0e2db0f3f79540",
          "sha1": "40f21aa14613ee9a79efcdd71f8e0f54e814340b",
          "md5": "2237d14bed37728cc13af02ed67eba3b"
        }
      ]
    },
    {
      "name": "iosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "sha256-iosarm32-metadata.jar",
          "url": "sha256-iosarm32-unspecified-metadata.jar",
          "size": 261,
          "sha512": "9bb70273146dc9c9cf088fcd7bce9677e66a4356b61381efcb3d9bef6b2818d509772060a3b3f69cf49dac68a801d086f953d50019f8e803d9b7a720a5d8bdc7",
          "sha256": "4023299732f29f75d61845166190fda276bdbbc38c985a693bba35d9888cddb7",
          "sha1": "9df58aa1d633f5dc078352a12920a3f07abf3468",
          "md5": "e2b0c7c49df16119f833b0982ed991fb"
        }
      ]
    }
  ]
}
