{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-bip39/1.0.2-SNAPSHOT/kotlin-bip39-1.0.2-SNAPSHOT.module",
    "group": "cash.z.ecc.android",
    "module": "kotlin-bip39",
    "version": "1.0.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "kotlin-bip39-macosx64-1.0.2-SNAPSHOT.klib",
          "size": 53549,
          "sha512": "cb1d45120ae3a0cc2c2cee774772504645adb105b2d77426e927f16b326165552acec1094f67521aca4d55ed6049fa7edfa9578ff8e3bf0e7bfd49b7dd45b2ad",
          "sha256": "66b1941c15d8f57a06c16a111c6963bc798c6479b64ab1b1592f16e46b4ddce9",
          "sha1": "4aa37a7437a1f098592fe2fd0bfe58fa574b1932",
          "md5": "bb7a5cc0e24ae9b964d83a25d86a9602"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-macosx64-1.0.2-SNAPSHOT-metadata.jar",
          "url": "kotlin-bip39-macosx64-1.0.2-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "c05676a3bdb7eb832a1137b2b26d4637c229c0d83a297d393ef6cce795b5dd06d9c2a8f30911275d10d146f10aec0da9616f7a693e6664a56db6f6e1ccd15695",
          "sha256": "07bebc3b7a570c263e7523912f2fb6bd3fe119e8bcccb81e8f16d5765eea52c7",
          "sha1": "897e1b7162068975bfd3777e10506378c9db4328",
          "md5": "59a24947a047d5216c4ec01d9fbd6319"
        }
      ]
    }
  ]
}
