{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-bip39/1.0.2-SNAPSHOT/kotlin-bip39-1.0.2-SNAPSHOT.module",
    "group": "cash.z.ecc.android",
    "module": "kotlin-bip39",
    "version": "1.0.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "kotlin-bip39-iosarm64-1.0.2-SNAPSHOT.klib",
          "size": 53503,
          "sha512": "d1f63326dbd32939b32404aa4120a3b402e2fc14b686224e5d03f59ec65553f01a900123dbb390573aa9566aa5390ee50d2f23f2f99fa4dad9d14e6eb4a2dc52",
          "sha256": "61cac716297cbb4e22116f8aec4b595bb7935607a8131af1a369c0574cafe457",
          "sha1": "944848157f70cfa6543b5167d0621c788727aa5f",
          "md5": "ccdc7365c4c93147d2467f27634f6f5c"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-iosarm64-1.0.2-SNAPSHOT-metadata.jar",
          "url": "kotlin-bip39-iosarm64-1.0.2-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "5b57ca4cff1399d67bc76a3b89b3aff3c5e32fcb72299cb511548b185b4761dd62b558ae062566256b10aac80a930c491544f3243e6f249204705eec04f1bef7",
          "sha256": "4855882e4b2a4163d80f1138505921ae411faa133b70a75ea1c0d8d558e6785d",
          "sha1": "19c0812f0c54348f1f5ac384c11755a28c606849",
          "md5": "5244351a9ded08095cf0632ab6ce39e3"
        }
      ]
    }
  ]
}
