{
  "formatVersion": "1.1",
  "component": {
    "group": "KHash",
    "module": "keccak",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "keccak-metadata.jar",
          "url": "keccak-unspecified.jar",
          "size": 5648,
          "sha512": "c284ca618e01edc7b198d91dc082cbfd2da2e7ef8f3cee87a3e9edbca95da890651dd8da05d1520dd8b363c50c586697699459cf8e229eef3e6891fd27d029fc",
          "sha256": "e0b5fd74d4a52079f1ce185ac69bc999652db875fb9e4a71b8f341caba58bf8f",
          "sha1": "19a7845064e1b14b575e0cc234d8e5475eec12c6",
          "md5": "8a6ed58b6ecfa28faadbd326e306b48f"
        }
      ]
    },
    {
      "name": "iosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../keccak-iosarm32/unspecified/keccak-iosarm32-unspecified.module",
        "group": "KHash",
        "module": "keccak-iosarm32",
        "version": "unspecified"
      }
    },
    {
      "name": "iosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../keccak-iosarm32/unspecified/keccak-iosarm32-unspecified.module",
        "group": "KHash",
        "module": "keccak-iosarm32",
        "version": "unspecified"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../keccak-iosarm64/unspecified/keccak-iosarm64-unspecified.module",
        "group": "KHash",
        "module": "keccak-iosarm64",
        "version": "unspecified"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../keccak-iosarm64/unspecified/keccak-iosarm64-unspecified.module",
        "group": "KHash",
        "module": "keccak-iosarm64",
        "version": "unspecified"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../keccak-iossimulatorarm64/unspecified/keccak-iossimulatorarm64-unspecified.module",
        "group": "KHash",
        "module": "keccak-iossimulatorarm64",
        "version": "unspecified"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../keccak-iossimulatorarm64/unspecified/keccak-iossimulatorarm64-unspecified.module",
        "group": "KHash",
        "module": "keccak-iossimulatorarm64",
        "version": "unspecified"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../keccak-iosx64/unspecified/keccak-iosx64-unspecified.module",
        "group": "KHash",
        "module": "keccak-iosx64",
        "version": "unspecified"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../keccak-iosx64/unspecified/keccak-iosx64-unspecified.module",
        "group": "KHash",
        "module": "keccak-iosx64",
        "version": "unspecified"
      }
    },
    {
      "name": "jsLegacyApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../keccak-js/unspecified/keccak-js-unspecified.module",
        "group": "KHash",
        "module": "keccak-js",
        "version": "unspecified"
      }
    },
    {
      "name": "jsLegacyRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../keccak-js/unspecified/keccak-js-unspecified.module",
        "group": "KHash",
        "module": "keccak-js",
        "version": "unspecified"
      }
    },
    {
      "name": "jsIrApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../keccak-js/unspecified/keccak-js-unspecified.module",
        "group": "KHash",
        "module": "keccak-js",
        "version": "unspecified"
      }
    },
    {
      "name": "jsIrRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../keccak-js/unspecified/keccak-js-unspecified.module",
        "group": "KHash",
        "module": "keccak-js",
        "version": "unspecified"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../keccak-jvm/unspecified/keccak-jvm-unspecified.module",
        "group": "KHash",
        "module": "keccak-jvm",
        "version": "unspecified"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../keccak-jvm/unspecified/keccak-jvm-unspecified.module",
        "group": "KHash",
        "module": "keccak-jvm",
        "version": "unspecified"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../keccak-linuxx64/unspecified/keccak-linuxx64-unspecified.module",
        "group": "KHash",
        "module": "keccak-linuxx64",
        "version": "unspecified"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../keccak-macosarm64/unspecified/keccak-macosarm64-unspecified.module",
        "group": "KHash",
        "module": "keccak-macosarm64",
        "version": "unspecified"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../keccak-macosarm64/unspecified/keccak-macosarm64-unspecified.module",
        "group": "KHash",
        "module": "keccak-macosarm64",
        "version": "unspecified"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../keccak-macosx64/unspecified/keccak-macosx64-unspecified.module",
        "group": "KHash",
        "module": "keccak-macosx64",
        "version": "unspecified"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../keccak-macosx64/unspecified/keccak-macosx64-unspecified.module",
        "group": "KHash",
        "module": "keccak-macosx64",
        "version": "unspecified"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../keccak-tvosarm64/unspecified/keccak-tvosarm64-unspecified.module",
        "group": "KHash",
        "module": "keccak-tvosarm64",
        "version": "unspecified"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../keccak-tvosarm64/unspecified/keccak-tvosarm64-unspecified.module",
        "group": "KHash",
        "module": "keccak-tvosarm64",
        "version": "unspecified"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../keccak-tvossimulatorarm64/unspecified/keccak-tvossimulatorarm64-unspecified.module",
        "group": "KHash",
        "module": "keccak-tvossimulatorarm64",
        "version": "unspecified"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../keccak-tvossimulatorarm64/unspecified/keccak-tvossimulatorarm64-unspecified.module",
        "group": "KHash",
        "module": "keccak-tvossimulatorarm64",
        "version": "unspecified"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../keccak-tvosx64/unspecified/keccak-tvosx64-unspecified.module",
        "group": "KHash",
        "module": "keccak-tvosx64",
        "version": "unspecified"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../keccak-tvosx64/unspecified/keccak-tvosx64-unspecified.module",
        "group": "KHash",
        "module": "keccak-tvosx64",
        "version": "unspecified"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../keccak-watchosarm32/unspecified/keccak-watchosarm32-unspecified.module",
        "group": "KHash",
        "module": "keccak-watchosarm32",
        "version": "unspecified"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../keccak-watchosarm32/unspecified/keccak-watchosarm32-unspecified.module",
        "group": "KHash",
        "module": "keccak-watchosarm32",
        "version": "unspecified"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../keccak-watchosarm64/unspecified/keccak-watchosarm64-unspecified.module",
        "group": "KHash",
        "module": "keccak-watchosarm64",
        "version": "unspecified"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../keccak-watchosarm64/unspecified/keccak-watchosarm64-unspecified.module",
        "group": "KHash",
        "module": "keccak-watchosarm64",
        "version": "unspecified"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../keccak-watchossimulatorarm64/unspecified/keccak-watchossimulatorarm64-unspecified.module",
        "group": "KHash",
        "module": "keccak-watchossimulatorarm64",
        "version": "unspecified"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../keccak-watchossimulatorarm64/unspecified/keccak-watchossimulatorarm64-unspecified.module",
        "group": "KHash",
        "module": "keccak-watchossimulatorarm64",
        "version": "unspecified"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../keccak-watchosx64/unspecified/keccak-watchosx64-unspecified.module",
        "group": "KHash",
        "module": "keccak-watchosx64",
        "version": "unspecified"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../keccak-watchosx64/unspecified/keccak-watchosx64-unspecified.module",
        "group": "KHash",
        "module": "keccak-watchosx64",
        "version": "unspecified"
      }
    },
    {
      "name": "watchosX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../keccak-watchosx86/unspecified/keccak-watchosx86-unspecified.module",
        "group": "KHash",
        "module": "keccak-watchosx86",
        "version": "unspecified"
      }
    },
    {
      "name": "watchosX86MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../keccak-watchosx86/unspecified/keccak-watchosx86-unspecified.module",
        "group": "KHash",
        "module": "keccak-watchosx86",
        "version": "unspecified"
      }
    }
  ]
}
