{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-bip39/1.0.2-SNAPSHOT/kotlin-bip39-1.0.2-SNAPSHOT.module",
    "group": "cash.z.ecc.android",
    "module": "kotlin-bip39",
    "version": "1.0.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "kotlin-bip39-iosx64-1.0.2-SNAPSHOT.klib",
          "size": 53487,
          "sha512": "e20f230b89ef625ce257e0cb03f0e4c94543b1d9072b88926df1f0429a4c7b2125bb2e91790b2636b42df6889c99090b8561b241101ec6d3fe219fde2703b751",
          "sha256": "1b5d2611284853d66afae2ee84cb52d186e83277d016c36748ec90482c977c9e",
          "sha1": "47a25555056e0d0b85787a5ee5edf7a2ee7d525d",
          "md5": "a0590911266dce5a398912b5f344fb4d"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-iosx64-1.0.2-SNAPSHOT-metadata.jar",
          "url": "kotlin-bip39-iosx64-1.0.2-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "5b57ca4cff1399d67bc76a3b89b3aff3c5e32fcb72299cb511548b185b4761dd62b558ae062566256b10aac80a930c491544f3243e6f249204705eec04f1bef7",
          "sha256": "4855882e4b2a4163d80f1138505921ae411faa133b70a75ea1c0d8d558e6785d",
          "sha1": "19c0812f0c54348f1f5ac384c11755a28c606849",
          "md5": "5244351a9ded08095cf0632ab6ce39e3"
        }
      ]
    }
  ]
}
