{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-bip39/1.0.2-SNAPSHOT/kotlin-bip39-1.0.2-SNAPSHOT.module",
    "group": "cash.z.ecc.android",
    "module": "kotlin-bip39",
    "version": "1.0.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "watchosX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "kotlin-bip39-watchosx86-1.0.2-SNAPSHOT.klib",
          "size": 53465,
          "sha512": "8746e24c5d44eaf4861b10252a7c9e58dd2fb35fa35a8c824a0c3df2d8dfe2e421879bc35c5cc97b03427e98325ab83d548d8b9bb81d78bd25bf17bcbc1fbbeb",
          "sha256": "8905dcc0ddb339342418d94bd8053186f24f6a483166a072d2dcf58947c2d8f2",
          "sha1": "54e8918dbb8d824e9a768a2bc3c4e35ecedd96be",
          "md5": "c515fb50703a8503534d7d69d69ffb18"
        }
      ]
    },
    {
      "name": "watchosX86MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-watchosx86-1.0.2-SNAPSHOT-metadata.jar",
          "url": "kotlin-bip39-watchosx86-1.0.2-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "c05676a3bdb7eb832a1137b2b26d4637c229c0d83a297d393ef6cce795b5dd06d9c2a8f30911275d10d146f10aec0da9616f7a693e6664a56db6f6e1ccd15695",
          "sha256": "07bebc3b7a570c263e7523912f2fb6bd3fe119e8bcccb81e8f16d5765eea52c7",
          "sha1": "897e1b7162068975bfd3777e10506378c9db4328",
          "md5": "59a24947a047d5216c4ec01d9fbd6319"
        }
      ]
    }
  ]
}
