{
  "formatVersion": "1.1",
  "component": {
    "url": "../../keccak/unspecified/keccak-unspecified.module",
    "group": "KHash",
    "module": "keccak",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "com.ionspin.kotlin",
          "module": "bignum",
          "version": {
            "requires": "0.3.4"
          }
        }
      ],
      "files": [
        {
          "name": "keccak.klib",
          "url": "keccak-watchosx64-unspecified.klib",
          "size": 22112,
          "sha512": "3f516c4f410db32a2cf8ce7225dae084c04b743c509f9c17f4b2ebe0ee4e4bf13d52079cff2f214b57948f3615023c5e58c83829dec571d079070e1c951aa6b6",
          "sha256": "ead860e0ba00ae209eb06e0891482e12e5cb66458ae38ef6d1cd8db0342dfb17",
          "sha1": "f2754f47e741d70a3c6187759e90100374f4a5f8",
          "md5": "431dfe5926e4110e7cb227d301b07e0c"
        }
      ]
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "com.ionspin.kotlin",
          "module": "bignum",
          "version": {
            "requires": "0.3.4"
          }
        }
      ],
      "files": [
        {
          "name": "keccak-watchosx64-metadata.jar",
          "url": "keccak-watchosx64-unspecified-metadata.jar",
          "size": 261,
          "sha512": "de7c12646a4023afd5d454beac09ec0cb3aca5b48b4c6d6c9e8e2f1572a1dc83894d05f93ca6424c276805e0655cfcff50f4f836851f0cd04b2be8be3eb63409",
          "sha256": "e8d373a823ffdd56180e41c6a9304edba958e6f4afec913e8cdf5587791db496",
          "sha1": "42c5f7e72ae5084c0db87a8d37e460b28bae8271",
          "md5": "e3d1a6767a85f1abcef97975f64c1e65"
        }
      ]
    }
  ]
}
