{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ripemd160/unspecified/ripemd160-unspecified.module",
    "group": "KHash",
    "module": "ripemd160",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jsLegacyApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "ripemd160-jslegacy.jar",
          "url": "ripemd160-js-unspecified.jar",
          "size": 12973,
          "sha512": "07a00f09413f0fbe4cf2bb0f59d960f2b5b1eb486266c34db3a3ee3824b658ec2d0ace9c44105eee3fbcba11f5abeda6d56769820fe574af2cf38f383f7e4ae3",
          "sha256": "4fa6e0dbec81d41906b44817b4236e4ae23049d8a50b8289b0b701ccc8b4f9eb",
          "sha1": "eec680ca1bc774457fc0221ca6f2864cc6a47ffa",
          "md5": "639fd513d98042290f628401856fbb11"
        }
      ]
    },
    {
      "name": "jsLegacyRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "ripemd160-jslegacy.jar",
          "url": "ripemd160-js-unspecified.jar",
          "size": 12973,
          "sha512": "07a00f09413f0fbe4cf2bb0f59d960f2b5b1eb486266c34db3a3ee3824b658ec2d0ace9c44105eee3fbcba11f5abeda6d56769820fe574af2cf38f383f7e4ae3",
          "sha256": "4fa6e0dbec81d41906b44817b4236e4ae23049d8a50b8289b0b701ccc8b4f9eb",
          "sha1": "eec680ca1bc774457fc0221ca6f2864cc6a47ffa",
          "md5": "639fd513d98042290f628401856fbb11"
        }
      ]
    },
    {
      "name": "jsIrApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "ripemd160-jsir.klib",
          "url": "ripemd160-js-unspecified.klib",
          "size": 35430,
          "sha512": "1c4f4d9c16d0adb8543d6329e7bdf7b9448bdb674dae7f13d8805b3d94f4965c6deeeb684b2ea5bbe0cc80b7816f1d6529a767310664bd9b1493f3dafd03ac16",
          "sha256": "20635067edd7e882696849523d6cbf78a84bb5449f4934571228f2a4ec9f4ab9",
          "sha1": "5a6958d2338dda075c0458a8cce4eb842b257f68",
          "md5": "2bb9df3379e60f7b0f3efca3d3fcc255"
        }
      ]
    },
    {
      "name": "jsIrRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "ripemd160-jsir.klib",
          "url": "ripemd160-js-unspecified.klib",
          "size": 35430,
          "sha512": "1c4f4d9c16d0adb8543d6329e7bdf7b9448bdb674dae7f13d8805b3d94f4965c6deeeb684b2ea5bbe0cc80b7816f1d6529a767310664bd9b1493f3dafd03ac16",
          "sha256": "20635067edd7e882696849523d6cbf78a84bb5449f4934571228f2a4ec9f4ab9",
          "sha1": "5a6958d2338dda075c0458a8cce4eb842b257f68",
          "md5": "2bb9df3379e60f7b0f3efca3d3fcc255"
        }
      ]
    }
  ]
}
