{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ripemd160/unspecified/ripemd160-unspecified.module",
    "group": "KHash",
    "module": "ripemd160",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "ripemd160.klib",
          "url": "ripemd160-watchosx64-unspecified.klib",
          "size": 38270,
          "sha512": "378d60e6d20db062c2c00a5763c1384171d3386e08c0e5cdd0436b829ded11dbd6d06b2b338bb205406f8ace504b076def28047abf9e755ad06afef37fdb3476",
          "sha256": "0ba6c428fcd834bcc84c5ce4b905ef5a57e8c8db602977c8bb6f6472704debbc",
          "sha1": "3eaf5e64cf35df60aed33e1954f3e4d1bcbd646d",
          "md5": "1d90616c287216442a9fcb6e4fff1019"
        }
      ]
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "ripemd160-watchosx64-metadata.jar",
          "url": "ripemd160-watchosx64-unspecified-metadata.jar",
          "size": 261,
          "sha512": "f7384db1400a7f610d96d99a7dafde081f3ab4fe45b92bb6847c66b267a167a6b79052b83feddfdb1353f4dc37578a11aa054d7448de127232933d5f8ba49e9d",
          "sha256": "99a96a6bb1be481352b379c42cdb6541d3f1adab7a016f195fb0edb2950b2125",
          "sha1": "891b737ec2c2fa2054110755d125c37b71d3155d",
          "md5": "b786c55926432e48a1325936f048808e"
        }
      ]
    }
  ]
}
