{
  "formatVersion": "1.1",
  "component": {
    "url": "../../keccak/unspecified/keccak-unspecified.module",
    "group": "KHash",
    "module": "keccak",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "com.ionspin.kotlin",
          "module": "bignum",
          "version": {
            "requires": "0.3.4"
          }
        }
      ],
      "files": [
        {
          "name": "keccak.klib",
          "url": "keccak-iosx64-unspecified.klib",
          "size": 22077,
          "sha512": "bf31fdebff3f2648e1f250a2cf2f8bae3b646ae3f06e4fe866060173d3f07c58c9af37f761f3f3062e4a4290994df1075b153a9ae8c94c9cd65bfd4788c20d63",
          "sha256": "0301ce71a3deb8c4e4788662dec0e662e77c8d85d80de1e596079e64aed0c407",
          "sha1": "07c647dbc53704d48e9f5de355530e1749cc8c5d",
          "md5": "ed2e5bec5a67d1725b77cc12c5b7e853"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "com.ionspin.kotlin",
          "module": "bignum",
          "version": {
            "requires": "0.3.4"
          }
        }
      ],
      "files": [
        {
          "name": "keccak-iosx64-metadata.jar",
          "url": "keccak-iosx64-unspecified-metadata.jar",
          "size": 261,
          "sha512": "de7c12646a4023afd5d454beac09ec0cb3aca5b48b4c6d6c9e8e2f1572a1dc83894d05f93ca6424c276805e0655cfcff50f4f836851f0cd04b2be8be3eb63409",
          "sha256": "e8d373a823ffdd56180e41c6a9304edba958e6f4afec913e8cdf5587791db496",
          "sha1": "42c5f7e72ae5084c0db87a8d37e460b28bae8271",
          "md5": "e3d1a6767a85f1abcef97975f64c1e65"
        }
      ]
    }
  ]
}
