{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ripemd160/unspecified/ripemd160-unspecified.module",
    "group": "KHash",
    "module": "ripemd160",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "ripemd160.klib",
          "url": "ripemd160-macosarm64-unspecified.klib",
          "size": 38269,
          "sha512": "544428cfe3957f4d0965e1571ed5cabdf453f9e600d772922e88e2a18b16fc9b58dd621081f1145648b7f4d2a294d178abef34a08b1e9ee2f5636d1b5ccdf590",
          "sha256": "95dc0fe8fcdeb3569b5dcb1a83d94e0c23c3a0febd2c6560210a4e299753a0fb",
          "sha1": "6b31762cbbd797444d7ea515cea6a9bd7fd33a2c",
          "md5": "70d2cdc7cc722fa5cd537ebfc727b531"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "ripemd160-macosarm64-metadata.jar",
          "url": "ripemd160-macosarm64-unspecified-metadata.jar",
          "size": 261,
          "sha512": "f7384db1400a7f610d96d99a7dafde081f3ab4fe45b92bb6847c66b267a167a6b79052b83feddfdb1353f4dc37578a11aa054d7448de127232933d5f8ba49e9d",
          "sha256": "99a96a6bb1be481352b379c42cdb6541d3f1adab7a016f195fb0edb2950b2125",
          "sha1": "891b737ec2c2fa2054110755d125c37b71d3155d",
          "md5": "b786c55926432e48a1325936f048808e"
        }
      ]
    }
  ]
}
