{
  "formatVersion": "1.1",
  "component": {
    "url": "../../keccak/unspecified/keccak-unspecified.module",
    "group": "KHash",
    "module": "keccak",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "com.ionspin.kotlin",
          "module": "bignum",
          "version": {
            "requires": "0.3.4"
          }
        }
      ],
      "files": [
        {
          "name": "keccak.klib",
          "url": "keccak-linuxx64-unspecified.klib",
          "size": 22094,
          "sha512": "b704186896c497423f473aed1b584bd3dad8f64c5469bc01a15fca7e32308ebb3c63aea4495a797660eae0f4d8d2fbb3a4584b105bc7a0405f7e49e393314cf1",
          "sha256": "67208ba3c9387cc15a5d249f4a67f5da864fc5dd5ce2d9673ba65decfc8175d4",
          "sha1": "1030756025e3c13fb1ce0941c99a2cc8a72720f7",
          "md5": "04008eafcb7f12a9d62a7e64494e406b"
        }
      ]
    }
  ]
}
