{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sha512/unspecified/sha512-unspecified.module",
    "group": "KHash",
    "module": "sha512",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "sha512-jvm.jar",
          "url": "sha512-jvm-unspecified.jar",
          "size": 11038,
          "sha512": "03a3beb8a34aa943a9cb301f64a9c219ed5fb21ae67d332ecb3b0728ab98ee804fb07f6f0678d29ca4a9cc0b2677379065ef70b18caa1674a6a8586a12966a92",
          "sha256": "ede26355490cd59d35527647cd05aa433750c2f8c58fdc0ba09822b46da8f72a",
          "sha1": "54346170ade82c7f22c5b249689a303854436915",
          "md5": "0f6031edfef5e14f69757b719d2784c3"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "sha512-jvm.jar",
          "url": "sha512-jvm-unspecified.jar",
          "size": 11038,
          "sha512": "03a3beb8a34aa943a9cb301f64a9c219ed5fb21ae67d332ecb3b0728ab98ee804fb07f6f0678d29ca4a9cc0b2677379065ef70b18caa1674a6a8586a12966a92",
          "sha256": "ede26355490cd59d35527647cd05aa433750c2f8c58fdc0ba09822b46da8f72a",
          "sha1": "54346170ade82c7f22c5b249689a303854436915",
          "md5": "0f6031edfef5e14f69757b719d2784c3"
        }
      ]
    }
  ]
}
