{
  "formatVersion": "1.1",
  "component": {
    "url": "../../keccak/unspecified/keccak-unspecified.module",
    "group": "KHash",
    "module": "keccak",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "keccak-jvm.jar",
          "url": "keccak-jvm-unspecified.jar",
          "size": 10418,
          "sha512": "66ea04f9ff62f439a3a4499df3a350c4da6a54a4d8dc907b1c904adc6ec7b753a8b810ad75681821fd4f8ce3d31ca46377d37503cbf95135251f19daa0f28c61",
          "sha256": "2531abb2403e1230aea155042ef555fa4caea54be319ee4730ebbe87925a7452",
          "sha1": "b715d95ded21081013fea628d6edcbf49427df3b",
          "md5": "e0ac52097208c5c70728b554fbaac406"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "com.ionspin.kotlin",
          "module": "bignum",
          "version": {
            "requires": "0.3.4"
          }
        }
      ],
      "files": [
        {
          "name": "keccak-jvm.jar",
          "url": "keccak-jvm-unspecified.jar",
          "size": 10418,
          "sha512": "66ea04f9ff62f439a3a4499df3a350c4da6a54a4d8dc907b1c904adc6ec7b753a8b810ad75681821fd4f8ce3d31ca46377d37503cbf95135251f19daa0f28c61",
          "sha256": "2531abb2403e1230aea155042ef555fa4caea54be319ee4730ebbe87925a7452",
          "sha1": "b715d95ded21081013fea628d6edcbf49427df3b",
          "md5": "e0ac52097208c5c70728b554fbaac406"
        }
      ]
    }
  ]
}
