{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ripemd160/unspecified/ripemd160-unspecified.module",
    "group": "KHash",
    "module": "ripemd160",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "ripemd160.klib",
          "url": "ripemd160-iosx64-unspecified.klib",
          "size": 38235,
          "sha512": "4dd5cce533fcb6dcc0a859a1574e2211b3e99e0fa6f344ec4fc81440c5cfb8d62f5976c4f169473c3014f9572b854a2713306d4c29b3da88b9b9567b37f7d419",
          "sha256": "c647361fa87fd67f73923ef66d23a137174fe7e46c3a2cd5611c899bafb6b77a",
          "sha1": "b25c071ae38d65fff4b35dba68d6b38a7e6b13c2",
          "md5": "33187b791789947ba5723e72a98ee1cc"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "ripemd160-iosx64-metadata.jar",
          "url": "ripemd160-iosx64-unspecified-metadata.jar",
          "size": 261,
          "sha512": "f7384db1400a7f610d96d99a7dafde081f3ab4fe45b92bb6847c66b267a167a6b79052b83feddfdb1353f4dc37578a11aa054d7448de127232933d5f8ba49e9d",
          "sha256": "99a96a6bb1be481352b379c42cdb6541d3f1adab7a016f195fb0edb2950b2125",
          "sha1": "891b737ec2c2fa2054110755d125c37b71d3155d",
          "md5": "b786c55926432e48a1325936f048808e"
        }
      ]
    }
  ]
}
