{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ripemd160/unspecified/ripemd160-unspecified.module",
    "group": "KHash",
    "module": "ripemd160",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "watchosX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "ripemd160.klib",
          "url": "ripemd160-watchosx86-unspecified.klib",
          "size": 38270,
          "sha512": "54f2ecf95f5be7d5a9b56cab55b9eb30688c5b8d1e5c7c2928035bfba2a832ac65084d916e5fb2b1b86545cb296adc275718c131d35151eb1a02fcd18615f691",
          "sha256": "b18bd0a1bfa7a26b62c5bc2e0dad5f7bc63e17edb67536bc85123e8daf6000ad",
          "sha1": "801a251a5794b3ce2fa9ab8620a54aba7849c6c3",
          "md5": "6945e21aeabe239fa2dadcbe94fabde1"
        }
      ]
    },
    {
      "name": "watchosX86MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "ripemd160-watchosx86-metadata.jar",
          "url": "ripemd160-watchosx86-unspecified-metadata.jar",
          "size": 261,
          "sha512": "f7384db1400a7f610d96d99a7dafde081f3ab4fe45b92bb6847c66b267a167a6b79052b83feddfdb1353f4dc37578a11aa054d7448de127232933d5f8ba49e9d",
          "sha256": "99a96a6bb1be481352b379c42cdb6541d3f1adab7a016f195fb0edb2950b2125",
          "sha1": "891b737ec2c2fa2054110755d125c37b71d3155d",
          "md5": "b786c55926432e48a1325936f048808e"
        }
      ]
    }
  ]
}
