{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ripemd160/unspecified/ripemd160-unspecified.module",
    "group": "KHash",
    "module": "ripemd160",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "ripemd160.klib",
          "url": "ripemd160-tvossimulatorarm64-unspecified.klib",
          "size": 38347,
          "sha512": "00ffc1473e8e641305329136d7ae4920b4f47ad0087db9c0809eb19c8419f209b3821faf697c5dcf4e17fa0162cd66a41c60e21ce34143efa822a9c6cfc465da",
          "sha256": "0be3cf61314ef02809fd8e26fe9896cb3f71f11b4e65b02ab227509098073cf3",
          "sha1": "11aa46358229edadc4551117e4d02127b152ac67",
          "md5": "5100e1564661a97885ce9aa1ffcd0f5a"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "ripemd160-tvossimulatorarm64-metadata.jar",
          "url": "ripemd160-tvossimulatorarm64-unspecified-metadata.jar",
          "size": 261,
          "sha512": "f7384db1400a7f610d96d99a7dafde081f3ab4fe45b92bb6847c66b267a167a6b79052b83feddfdb1353f4dc37578a11aa054d7448de127232933d5f8ba49e9d",
          "sha256": "99a96a6bb1be481352b379c42cdb6541d3f1adab7a016f195fb0edb2950b2125",
          "sha1": "891b737ec2c2fa2054110755d125c37b71d3155d",
          "md5": "b786c55926432e48a1325936f048808e"
        }
      ]
    }
  ]
}
