{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sha256/unspecified/sha256-unspecified.module",
    "group": "KHash",
    "module": "sha256",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "sha256-jvm.jar",
          "url": "sha256-jvm-unspecified.jar",
          "size": 10441,
          "sha512": "2ee9838cda8fa412d1f3be12e4a4a5694503c3b1b71e7e53222a09a218dc2c9f172d28f903da7785eb9d48b608c61cef3614e35aa320c95072d9c8c226a0adc1",
          "sha256": "573e17a5a5fb49834bb725b984f6c91b9a09bd4b06290b17d7d05ffc89580f90",
          "sha1": "9bfb3f751bf6ac311af7ef26f3df30df65c3adf2",
          "md5": "26db48bbdb2958794d3eaf326e1cdbf8"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "sha256-jvm.jar",
          "url": "sha256-jvm-unspecified.jar",
          "size": 10441,
          "sha512": "2ee9838cda8fa412d1f3be12e4a4a5694503c3b1b71e7e53222a09a218dc2c9f172d28f903da7785eb9d48b608c61cef3614e35aa320c95072d9c8c226a0adc1",
          "sha256": "573e17a5a5fb49834bb725b984f6c91b9a09bd4b06290b17d7d05ffc89580f90",
          "sha1": "9bfb3f751bf6ac311af7ef26f3df30df65c3adf2",
          "md5": "26db48bbdb2958794d3eaf326e1cdbf8"
        }
      ]
    }
  ]
}
