{
  "formatVersion": "1.1",
  "component": {
    "url": "../../keccak/unspecified/keccak-unspecified.module",
    "group": "KHash",
    "module": "keccak",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jsLegacyApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "keccak-jslegacy.jar",
          "url": "keccak-js-unspecified.jar",
          "size": 79088,
          "sha512": "3f8f781611ea764b29d8257f7f983e76fe4c82dbd2c28db354f66bb7366da70abf54a85e102a41c020c4c39d436f03b069d7fc8b0fec98eb7a8033deffa94aba",
          "sha256": "4e9b72d0e05fdf68db384a57e902b04014d24f1b7621d40d8aba08c4bd69427d",
          "sha1": "794bc7c1420d0103b26e58d4bed6d6dd5a681daa",
          "md5": "bd002bf85cc0c0e1dd80138bda13068a"
        }
      ]
    },
    {
      "name": "jsLegacyRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "com.ionspin.kotlin",
          "module": "bignum",
          "version": {
            "requires": "0.3.4"
          }
        }
      ],
      "files": [
        {
          "name": "keccak-jslegacy.jar",
          "url": "keccak-js-unspecified.jar",
          "size": 79088,
          "sha512": "3f8f781611ea764b29d8257f7f983e76fe4c82dbd2c28db354f66bb7366da70abf54a85e102a41c020c4c39d436f03b069d7fc8b0fec98eb7a8033deffa94aba",
          "sha256": "4e9b72d0e05fdf68db384a57e902b04014d24f1b7621d40d8aba08c4bd69427d",
          "sha1": "794bc7c1420d0103b26e58d4bed6d6dd5a681daa",
          "md5": "bd002bf85cc0c0e1dd80138bda13068a"
        }
      ]
    },
    {
      "name": "jsIrApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "com.ionspin.kotlin",
          "module": "bignum",
          "version": {
            "requires": "0.3.4"
          }
        }
      ],
      "files": [
        {
          "name": "keccak-jsir.klib",
          "url": "keccak-js-unspecified.klib",
          "size": 19566,
          "sha512": "68be148d2ea8f00c259d8150e542620878a1d48e884480a198b2b2fa6f516eb80e1d671fa3f7e9a48ed8f787bdcdb0c32333e8160c737cc2e9b452560b8c3807",
          "sha256": "76985c503c6fa3c01b0bcd96e80099a8b608dba8d7fcbc4801c4278b6eee68d7",
          "sha1": "15dfb607b6aa23a7bdd88be7479eee440f74623d",
          "md5": "e7e0f212c1b06b251e13b3732a10af47"
        }
      ]
    },
    {
      "name": "jsIrRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "com.ionspin.kotlin",
          "module": "bignum",
          "version": {
            "requires": "0.3.4"
          }
        }
      ],
      "files": [
        {
          "name": "keccak-jsir.klib",
          "url": "keccak-js-unspecified.klib",
          "size": 19566,
          "sha512": "68be148d2ea8f00c259d8150e542620878a1d48e884480a198b2b2fa6f516eb80e1d671fa3f7e9a48ed8f787bdcdb0c32333e8160c737cc2e9b452560b8c3807",
          "sha256": "76985c503c6fa3c01b0bcd96e80099a8b608dba8d7fcbc4801c4278b6eee68d7",
          "sha1": "15dfb607b6aa23a7bdd88be7479eee440f74623d",
          "md5": "e7e0f212c1b06b251e13b3732a10af47"
        }
      ]
    }
  ]
}
