{
  "formatVersion": "1.1",
  "component": {
    "url": "../../keccak/unspecified/keccak-unspecified.module",
    "group": "KHash",
    "module": "keccak",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "com.ionspin.kotlin",
          "module": "bignum",
          "version": {
            "requires": "0.3.4"
          }
        }
      ],
      "files": [
        {
          "name": "keccak.klib",
          "url": "keccak-watchossimulatorarm64-unspecified.klib",
          "size": 22213,
          "sha512": "89ed5dcd10df380b6de4b44c0c2f4424029a340554cc02331acf561105114c400d072065eb042a3e73abbbba8db4427c3f917ef2e769aca5f31a955792bca443",
          "sha256": "55e0224f8d8142292855a46141e8bf60ef22b56a68646d3223d4aa9d91770dca",
          "sha1": "5fd025a198c9f0a98f377fa98a08578f64519a89",
          "md5": "782b09586104ce913bf45e059b000398"
        }
      ]
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "com.ionspin.kotlin",
          "module": "bignum",
          "version": {
            "requires": "0.3.4"
          }
        }
      ],
      "files": [
        {
          "name": "keccak-watchossimulatorarm64-metadata.jar",
          "url": "keccak-watchossimulatorarm64-unspecified-metadata.jar",
          "size": 261,
          "sha512": "de7c12646a4023afd5d454beac09ec0cb3aca5b48b4c6d6c9e8e2f1572a1dc83894d05f93ca6424c276805e0655cfcff50f4f836851f0cd04b2be8be3eb63409",
          "sha256": "e8d373a823ffdd56180e41c6a9304edba958e6f4afec913e8cdf5587791db496",
          "sha1": "42c5f7e72ae5084c0db87a8d37e460b28bae8271",
          "md5": "e3d1a6767a85f1abcef97975f64c1e65"
        }
      ]
    }
  ]
}
