{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ripemd160/unspecified/ripemd160-unspecified.module",
    "group": "KHash",
    "module": "ripemd160",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "ripemd160.klib",
          "url": "ripemd160-linuxx64-unspecified.klib",
          "size": 38253,
          "sha512": "8574d38f0d2efe9dc360679f98f544346e35951bf89210dc6beebaee84b1291f608e455888bb80cfdd40c6f6ff171e08c0e5a48844ee87381536db70af2d3220",
          "sha256": "4874df2e37832e6b8561f9749e9875b69f2096a73a56584a2dd1a0ea1587d8b7",
          "sha1": "cc3a67de1e9a7e093b20af2ae51b7b54a2dc734e",
          "md5": "30a3010eb3710c77588afa2a09ef258f"
        }
      ]
    }
  ]
}
