{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sha256/unspecified/sha256-unspecified.module",
    "group": "KHash",
    "module": "sha256",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "sha256.klib",
          "url": "sha256-macosarm64-unspecified.klib",
          "size": 19397,
          "sha512": "b0313b5a2450b8bd26250d70935ac0867d4b7347ad91bba4e8e617f2ab3b9ad891cfc29b7345bd67e856870a1b5a04851f1a29d05a8f7846d7e152fd6096d350",
          "sha256": "4e1324d7ca1c2ad79beb4f09cf476e6fe04aa4c25d7fa7a85236c2cc6ca950ad",
          "sha1": "7ccc9e12b5b3a8ae12fd456f67e6cfd1437b95be",
          "md5": "093b2bd3fc64909ffba3858a75d61323"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "sha256-macosarm64-metadata.jar",
          "url": "sha256-macosarm64-unspecified-metadata.jar",
          "size": 261,
          "sha512": "9bb70273146dc9c9cf088fcd7bce9677e66a4356b61381efcb3d9bef6b2818d509772060a3b3f69cf49dac68a801d086f953d50019f8e803d9b7a720a5d8bdc7",
          "sha256": "4023299732f29f75d61845166190fda276bdbbc38c985a693bba35d9888cddb7",
          "sha1": "9df58aa1d633f5dc078352a12920a3f07abf3468",
          "md5": "e2b0c7c49df16119f833b0982ed991fb"
        }
      ]
    }
  ]
}
