{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-bip39/1.0.2-SNAPSHOT/kotlin-bip39-1.0.2-SNAPSHOT.module",
    "group": "cash.z.ecc.android",
    "module": "kotlin-bip39",
    "version": "1.0.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "kotlin-bip39-tvosarm64-1.0.2-SNAPSHOT.klib",
          "size": 53512,
          "sha512": "b8bee60a07228888cc6b20f642079ac6ae02ef40e5b9994c6ef1df36062da6dbad538b95134f43537c00eaad119b09303335abdf2ff187430beea6ac3f22b3a8",
          "sha256": "abcd5e13e2e5157c1a9e89fb58f3184dbb6aa38f6a5df2309df952d8a6094ae5",
          "sha1": "75a70dce4bb23643e6bb81fb95d09251ccf6ff1d",
          "md5": "efdd7a980de42bd69b382b9f9606c561"
        }
      ]
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-tvosarm64-1.0.2-SNAPSHOT-metadata.jar",
          "url": "kotlin-bip39-tvosarm64-1.0.2-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "c05676a3bdb7eb832a1137b2b26d4637c229c0d83a297d393ef6cce795b5dd06d9c2a8f30911275d10d146f10aec0da9616f7a693e6664a56db6f6e1ccd15695",
          "sha256": "07bebc3b7a570c263e7523912f2fb6bd3fe119e8bcccb81e8f16d5765eea52c7",
          "sha1": "897e1b7162068975bfd3777e10506378c9db4328",
          "md5": "59a24947a047d5216c4ec01d9fbd6319"
        }
      ]
    }
  ]
}
